export const ar = {
  appName: 'VoxBack',
  tagline: 'اسمعها. قلها بالعكس.',
  homeQuestion: 'هل تستطيع الكلام بالعكس؟',
  startGame: 'ابدأ اللعب',
  howToPlay: 'طريقة اللعب',
  settings: 'الإعدادات',
  gamesPlayed: 'الألعاب',
  bestScore: 'أفضل نتيجة',
  highestSimilarity: 'أعلى تشابه',
  perfectRounds: 'جولات مثالية',
  firstTimeTitle: 'كيف تعمل VoxBack',
  letsPlay: 'هيا نلعب!',
  tutorialRecordTitle: 'سجل',
  tutorialRecordBody: 'يسجل لاعب عبارة.',
  tutorialReverseTitle: 'اعكس',
  tutorialReverseBody: 'نعكس التسجيل الصوتي.',
  tutorialListenTitle: 'استمع',
  tutorialListenBody: 'يستمع اللاعب الآخر.',
  tutorialRepeatTitle: 'كرر',
  tutorialRepeatBody: 'حاول تقليد ما سمعته.',
  tutorialCompareTitle: 'قارن',
  tutorialCompareBody: 'نعكس محاولتك ونحسب نتيجتك.',
  playerSetupTitle: 'اختيار اللاعبين',
  playerSetupSubtitle: 'صوتان يدخلان. وبطل واحد للكلام بالعكس.',
  playerOne: 'اللاعب 1',
  playerTwo: 'اللاعب 2',
  playerName: 'اسم اللاعب',
  avatar: 'الصورة',
  continue: 'متابعة',
  gameSettingsTitle: 'إعدادات اللعبة',
  rounds: 'عدد الجولات',
  recordingDuration: 'مدة التسجيل',
  secondsShort: '{{count}} ث',
  difficulty: 'الصعوبة',
  easy: 'سهل',
  normal: 'عادي',
  hard: 'صعب',
  mode: 'النمط',
  freeMode: 'النمط الحر',
  challengeMode: 'نمط التحدي',
  freeModeHint: 'قل أي شيء تريده.',
  challengeModeHint: 'يعطي التطبيق عبارة لمنشئ الجولة.',
  startRound: 'ابدأ الجولة',
  roundTitle: 'الجولة {{round}}',
  creatorTurn: 'دور {{name}}',
  guesserTurn: 'دور {{name}}',
  creatorPrompt: 'سجل عبارة من أجل {{name}}.',
  challengePhrase: 'عبارة التحدي',
  privacyNote: 'أخف هذه الشاشة عن اللاعب الذي سيخمن.',
  tapToRecord: 'اضغط للتسجيل',
  getReady: 'استعد!',
  recordNow: 'سجل!',
  recording: 'جار التسجيل',
  stop: 'إيقاف',
  cancel: 'إلغاء',
  play: 'تشغيل',
  pause: 'إيقاف مؤقت',
  restart: 'إعادة',
  recordAgain: 'سجل مرة أخرى',
  useThisRecording: 'استخدم هذا التسجيل',
  yourRecording: 'تسجيلك',
  yourAttempt: 'محاولتك',
  minimumRecording: 'سجل لمدة 0.5 ثانية على الأقل.',
  maxDuration: 'الحد الأقصى {{seconds}} ثوان',
  reversingVoice: 'نعكس صوتك...',
  reversingAttempt: 'نعكس محاولتك...',
  analyzingVoice: 'نحلل الصوت...',
  passPhone: 'مرر الهاتف',
  passToPlayer: 'أعط الهاتف إلى {{name}}.',
  creatorDone: 'انتهى دور {{name}}.',
  imReady: 'أنا جاهز',
  listenCarefully: 'استمع جيداً...',
  listenOnlyReversed: 'ستسمع الصوت المعكوس فقط.',
  recordMyAttempt: 'سجل محاولتي',
  sayWhatYouHeard: 'الآن حاول قول ما سمعته تماماً!',
  yourTurn: 'دورك',
  continueToScore: 'متابعة',
  howClose: 'كم كنت قريباً؟',
  target: 'الهدف',
  yourReverse: 'صوتك المعكوس',
  playTarget: 'تشغيل الهدف',
  playAttempt: 'تشغيل المحاولة',
  playBoth: 'تشغيل الاثنين',
  similarity: 'التشابه',
  roundResults: 'نتائج الجولة {{round}}',
  match: 'تطابق {{score}}%',
  tryAgain: 'حاول مرة أخرى',
  nextRound: 'الجولة التالية',
  scoreboard: 'لوحة النتائج',
  player: 'اللاعب',
  score: 'النقاط',
  finalResults: 'النتائج النهائية',
  winner: 'فاز {{name}}!',
  draw: 'تعادل!',
  points: '{{score}} نقطة',
  averageSimilarity: 'متوسط التشابه',
  bestRound: 'أفضل جولة',
  highestScore: 'أعلى نتيجة',
  perfectRoundCount: 'الجولات المثالية',
  playAgain: 'العب مرة أخرى',
  newPlayers: 'لاعبون جدد',
  home: 'الرئيسية',
  shareResult: 'شارك النتيجة',
  shareText: 'هل تستطيع الفوز على هذه النتيجة؟',
  thatWasClose: 'كانت قريبة!',
  language: 'اللغة',
  english: 'English',
  arabic: 'العربية',
  soundEffects: 'المؤثرات الصوتية',
  music: 'الموسيقى',
  hapticFeedback: 'الاهتزاز',
  recordingQuality: 'جودة التسجيل',
  standard: 'قياسية',
  high: 'عالية',
  privacy: 'الخصوصية',
  about: 'حول التطبيق',
  on: 'تشغيل',
  off: 'إيقاف',
  privacyBody: 'تبقى التسجيلات الصوتية على هذا الجهاز. لا ترفع VoxBack التسجيلات وتحذف الصوت المؤقت عند نهاية اللعبة.',
  aboutBody: 'VoxBack لعبة صوتية محلية للتمرير بين الأصدقاء والعائلة.',
  microphoneDenied: 'يلزم السماح بالميكروفون لتسجيل صوتك.',
  openSettings: 'فتح الإعدادات',
  recordingFailed: 'فشل التسجيل. حاول مرة أخرى.',
  processingFailed: 'حدث خطأ أثناء معالجة التسجيل.',
  playbackFailed: 'تعذر تشغيل هذا التسجيل.',
  shareFailed: 'تعذر مشاركة بطاقة النتيجة.',
  retry: 'إعادة المحاولة',
  noGame: 'لا توجد لعبة نشطة.',
  back: 'رجوع',
  ready: 'جاهز',
  loading: 'جار التحميل',
  soundUnavailable: 'المؤثر الصوتي غير متاح.',
  reactionPerfect: 'مثالي! أصبحت متحدثاً عكسياً بشرياً!',
  reactionRidiculous: 'هذا قريب بشكل مذهل!',
  reactionBackwardsEars: 'أذناك العكسيتان تعملان!',
  reactionNotBad: 'ليس سيئاً!',
  reactionPractice: 'نحتاج إلى بعض التدريب.',
  reactionMystery: 'ماذا سمعنا للتو؟!',
  reactionPerfectShort: 'مثالي!',
  reactionIncredible: 'مذهل!',
  reactionVeryClose: 'قريب جداً!',
  reactionNotBadShort: 'ليس سيئاً!',
  reactionGettingThere: 'تتحسن!',
  reactionWhatWasThat: 'ما هذا؟!',
} as const;
