export const en = {
  appName: 'VoxBack',
  tagline: 'Hear it. Say it back.',
  homeQuestion: 'Can you speak backwards?',
  startGame: 'Start Game',
  howToPlay: 'How to Play',
  settings: 'Settings',
  gamesPlayed: 'Games Played',
  bestScore: 'Best Score',
  highestSimilarity: 'Highest Similarity',
  perfectRounds: 'Perfect Rounds',
  firstTimeTitle: 'How VoxBack Works',
  letsPlay: "Let's Play!",
  tutorialRecordTitle: 'Record',
  tutorialRecordBody: 'One player records a phrase.',
  tutorialReverseTitle: 'Reverse',
  tutorialReverseBody: 'We reverse the recording.',
  tutorialListenTitle: 'Listen',
  tutorialListenBody: 'The other player listens.',
  tutorialRepeatTitle: 'Repeat',
  tutorialRepeatBody: 'Try to reproduce what you heard.',
  tutorialCompareTitle: 'Compare',
  tutorialCompareBody: 'We reverse your attempt and calculate your score.',
  playerSetupTitle: 'Choose Players',
  playerSetupSubtitle: 'Two voices enter. One backwards champion leaves.',
  playerOne: 'Player 1',
  playerTwo: 'Player 2',
  playerName: 'Player Name',
  avatar: 'Avatar',
  continue: 'Continue',
  gameSettingsTitle: 'Game Settings',
  rounds: 'Number of Rounds',
  recordingDuration: 'Recording Duration',
  secondsShort: '{{count}}s',
  difficulty: 'Difficulty',
  easy: 'Easy',
  normal: 'Normal',
  hard: 'Hard',
  mode: 'Mode',
  freeMode: 'Free Mode',
  challengeMode: 'Challenge Mode',
  freeModeHint: 'Say anything you want.',
  challengeModeHint: 'The app gives the creator a phrase.',
  startRound: 'Start Round',
  roundTitle: 'Round {{round}}',
  creatorTurn: "{{name}}'s Turn",
  guesserTurn: "{{name}}'s Turn",
  creatorPrompt: 'Record a phrase for {{name}}.',
  challengePhrase: 'Challenge Phrase',
  privacyNote: 'Keep this screen private from the guesser.',
  tapToRecord: 'Tap to record',
  getReady: 'Get Ready!',
  recordNow: 'Record!',
  recording: 'Recording',
  stop: 'Stop',
  cancel: 'Cancel',
  play: 'Play',
  playRecording: 'Play Recording',
  pause: 'Pause',
  restart: 'Restart',
  recordAgain: 'Record Again',
  useThisRecording: 'Use This Recording',
  yourRecording: 'Your Recording',
  yourAttempt: 'Your Attempt',
  minimumRecording: 'Record at least 0.5 seconds.',
  maxDuration: 'Max {{seconds}} seconds',
  reversingVoice: 'Reversing your voice...',
  reversingAttempt: 'Reversing your attempt...',
  analyzingVoice: 'Analyzing voice...',
  passPhone: 'PASS THE PHONE',
  passToPlayer: 'Give the phone to {{name}}.',
  creatorDone: "{{name}}'s turn is complete.",
  imReady: "I'm Ready",
  listenCarefully: 'Listen carefully...',
  listenOnlyReversed: 'You can only hear the reversed target.',
  recordMyAttempt: 'Record My Attempt',
  sayWhatYouHeard: 'Now try to say exactly what you heard!',
  yourTurn: 'Your Turn',
  continueToScore: 'Continue',
  howClose: 'How Close Were You?',
  target: 'Target',
  yourReverse: 'Your Reverse',
  playTarget: 'Play Target',
  playAttempt: 'Play Attempt',
  playBoth: 'Play Both',
  similarity: 'Similarity',
  roundResults: 'Round {{round}} Results',
  match: '{{score}}% Match',
  tryAgain: 'Try Again',
  nextRound: 'Next Round',
  scoreboard: 'Scoreboard',
  player: 'Player',
  score: 'Score',
  finalResults: 'Final Results',
  seeFinalResults: 'See Final Results',
  winner: '{{name}} Wins!',
  draw: "It's a Draw!",
  points: '{{score}} points',
  averageSimilarity: 'Average similarity',
  bestRound: 'Best round',
  highestScore: 'Highest score',
  perfectRoundCount: 'Perfect rounds',
  playAgain: 'Play Again',
  newPlayers: 'New Players',
  home: 'Home',
  shareResult: 'Share Result',
  shareText: 'Can you beat this?',
  thatWasClose: 'That Was Close!',
  language: 'Language',
  english: 'English',
  arabic: 'Arabic',
  soundEffects: 'Sound Effects',
  music: 'Music',
  hapticFeedback: 'Haptic Feedback',
  recordingQuality: 'Recording Quality',
  standard: 'Standard',
  high: 'High',
  privacy: 'Privacy',
  about: 'About',
  on: 'On',
  off: 'Off',
  privacyBody: 'Voice recordings stay on this device. VoxBack never uploads recordings and deletes temporary audio when a game ends.',
  aboutBody: 'VoxBack is a local pass-and-play voice game for friends and family.',
  microphoneDenied: 'Microphone access is required to record your voice.',
  openSettings: 'Open Settings',
  recordingFailed: 'Recording failed. Please try again.',
  processingFailed: 'Something went wrong while processing the recording.',
  playbackFailed: 'Unable to play this recording.',
  shareFailed: 'Unable to share the result card.',
  retry: 'Retry',
  noGame: 'No active game yet.',
  back: 'Back',
  ready: 'Ready',
  loading: 'Loading',
  soundUnavailable: 'Sound effect unavailable.',
  reactionPerfect: 'PERFECT! You basically became a human reverse speaker!',
  reactionRidiculous: "That's ridiculously close!",
  reactionBackwardsEars: 'Your backwards ears are working!',
  reactionNotBad: 'Not bad!',
  reactionPractice: 'We may need some practice.',
  reactionMystery: 'What did we just hear?!',
  reactionPerfectShort: 'PERFECT!',
  reactionIncredible: 'Incredible!',
  reactionVeryClose: 'Very Close!',
  reactionNotBadShort: 'Not Bad!',
  reactionGettingThere: 'Getting There!',
  reactionWhatWasThat: 'What Was That?!',
} as const;
